module FlightGenerator

  @flights = [
    {
        airline: "SkyWest",
        flight_number: "3440",
        aircraft: "Embraer E175",
        origin: "SFO",
        departure_time: "8:50 PM PDT",
        destination: "LAX",
        arrival_time: "10:21 PM PDT",
    },
    {
        airline: "Southwest",
        flight_number: "1218",
        aircraft: "Boeing 737-700",
        origin: "SFO",
        departure_time: "8:15 PM PDT",
        destination: "LAX",
        arrival_time: "9:55 PM PDT",
    },
    {
        airline: "SkyWest",
        flight_number: "3671",
        aircraft: "Embraer E170",
        origin: "SFO",
        departure_time: "7:59 PM PDT",
        destination: "LAX",
        arrival_time: "9:40 PM PDT",
    },
    {
        airline: "SkyWest",
        flight_number: "3486",
        aircraft: "Embraer E175",
        origin: "SFO",
        departure_time: "7:25 PM PDT",
        destination: "LAX",
        arrival_time: "8:56 PM PDT"
    },
    {
        airline: "United",
        flight_number: "1200",
        aircraft: "Airbus A320",
        origin: "SFO",
        departure_time: "7:05 PM PDT",
        destination: "LAX",
        arrival_time: "8:30 PM PDT"
    },
    {
        airline: "SkyWest",
        flight_number: "3105",
        aircraft: "Bombardier CRJ700",
        origin: "SFO",
        departure_time: "6:48 PM PDT",
        destination: "LAX",
        arrival_time: "8:26 PM PDT"
    },
    {
        airline: "JetBlue",
        flight_number: "6135",
        aircraft: "Airbus A321",
        origin: "SFO",
        departure_time: "5:45 PM PDT",
        destination: "LAX",
        arrival_time: "7:10 PM PDT"
    },
    {
        airline: "JetBlue",
        flight_number: "2735",
        aircraft: "Airbus A320",
        origin: "SFO",
        departure_time: "5:44 PM PDT",
        destination: "LAX",
        arrival_time: "7:10 PM PDT"
    },
    {
        airline: "SkyWest",
        flight_number: "3643",
        aircraft: "Embraer E170",
        origin: "SFO",
        departure_time: "5:10 PM PDT",
        destination: "LAX",
        arrival_time: "6:50 PM PDT"
    },
    {
        airline: "SkyWest",
        flight_number: "3434",
        aircraft: "Embraer E175",
        origin: "SFO",
        departure_time: "3:15 PM PDT",
        destination: "LAX",
        arrival_time: "4:46 PM PDT"
    },
    {
        airline: "SkyWest",
        flight_number: "3456",
        aircraft: "Embraer E175",
        origin: "SFO",
        departure_time: "2:25 PM PDT",
        destination: "LAX",
        arrival_time: "3:55 PM PDT"
    },
    {
        airline: "United",
        flight_number: "2114",
        aircraft: "Boeing 737-700",
        origin: "SFO",
        departure_time: "1:55 PM PDT",
        destination: "LAX",
        arrival_time: "3:17 PM PDT"
    },
    {
        airline: "SkyWest",
        flight_number: "3571",
        aircraft: "Embraer E170",
        origin: "SFO",
        departure_time: "12:53 PM PDT",
        destination: "LAX",
        arrival_time: "2:29 PM PDT"
    },
    {
        airline: "JetBlue",
        flight_number: "2835",
        aircraft: "Airbus A320",
        origin: "SFO",
        departure_time: "12:49 PM PDT",
        destination: "LAX",
        arrival_time: "2:23 PM PDT",
    },
    {
        airline: "SkyWest",
        flight_number: "3444",
        aircraft: "Embraer E175",
        origin: "SFO",
        departure_time: "12:10 PM PDT",
        destination: "LAX",
        arrival_time: "1:40 PM PDT",
    },
    {
        airline: "SkyWest",
        flight_number: "3264",
        aircraft: "Bombardier CRJ700",
        origin: "SFO",
        departure_time: "10:40 AM PDT",
        destination: "LAX",
        arrival_time: "12:14 PM PDT",
    },
    {
        airline: "SkyWest",
        flight_number: "3432",
        aircraft: "Embraer E175",
        origin: "SFO",
        departure_time: "10:00 AM PDT",
        destination: "LAX",
        arrival_time: "11:30 AM PDT",
    },
    {
        airline: "SkyWest",
        flight_number: "3698",
        aircraft: "Embraer E170",
        origin: "SFO",
        departure_time: "9:24 AM PDT",
        destination: "LAX",
        arrival_time: "11:10 AM PDT",
    },
    {
        airline: "SkyWest",
        flight_number: "4737",
        aircraft: "Embraer E170",
        origin: "SFO",
        departure_time: "8:30 AM PDT",
        destination: "LAX",
        arrival_time: "9:55 AM PDT",
    },
    {
        airline: "SkyWest",
        flight_number: "3335",
        aircraft: "Embraer E175",
        origin: "SFO",
        departure_time: "8:05 AM PDT",
        destination: "LAX",
        arrival_time: "9:35 AM PDT",
    },
    {
        airline: "Southwest",
        flight_number: "3366",
        aircraft: "Boeing 737-800",
        origin: "SFO",
        departure_time: "7:45 AM PDT",
        destination: "LAX",
        arrival_time: "9:15 AM PDT",
    },
    {
        airline: "SkyWest",
        flight_number: "3816",
        aircraft: "Embraer E170",
        origin: "SFO",
        departure_time: "6:00 AM PDT",
        destination: "LAX",
        arrival_time: "7:30 AM PDT",
    },
    {
        airline: "SkyWest",
        flight_number: "3198",
        aircraft: "Bombardier CRJ700",
        origin: "SFO",
        departure_time: "6:00 AM PDT",
        destination: "LAX",
        arrival_time: "7:31 AM PDT",
    },
    {
        airline: "SkyWest",
        flight_number: "3318",
        aircraft: "Embraer E175",
        origin: "SFO",
        departure_time: "6:00 AM PDT",
        destination: "LAX",
        arrival_time: "7:30 AM PDT",
    },
    {
        airline: "Southwest",
        flight_number: "2637",
        aircraft: "Boeing 737-700",
        origin: "LAX",
        departure_time: "7:50 PM PDT",
        destination: "SFO",
        arrival_time: "9:15 PM PDT",
    },
    {
        airline: "United",
        flight_number: "1666",
        aircraft: "Boeing 737-800",
        origin: "LAX",
        departure_time: "7:20 PM PDT",
        destination: "SFO",
        arrival_time: "8:39 PM PDT",
    },
    {
        airline: "SkyWest",
        flight_number: "3325",
        aircraft: "Embraer E175",
        origin: "LAX",
        departure_time: "6:15 PM PDT",
        destination: "SFO",
        arrival_time: "7:46 PM PDT",
    },
    {
        airline: "SkyWest",
        flight_number: "3700",
        aircraft: "Embraer E170",
        origin: "LAX",
        departure_time: "5:37 PM PDT",
        destination: "SFO",
        arrival_time: "7:07 PM PDT",
    },
    {
        airline: "SkyWest",
        flight_number: "3295",
        aircraft: "Bombardier CRJ700",
        origin: "LAX",
        departure_time: "4:40 PM PDT",
        destination: "SFO",
        arrival_time: "6:13 PM PDT",
    },
    {
        airline: "SkyWest",
        flight_number: "3463",
        aircraft: "Embraer E175",
        origin: "LAX",
        departure_time: "4:35 PM PDT",
        destination: "SFO",
        arrival_time: "6:06 PM PDT",
    },
    {
        airline: "United",
        flight_number: "432",
        aircraft: "Airbus A320",
        origin: "LAX",
        departure_time: "4:01 PM PDT",
        destination: "SFO",
        arrival_time: "5:20 PM PDT",
    },
    {
        airline: "JetBlue",
        flight_number: "2736",
        aircraft: "Airbus A320",
        origin: "LAX",
        departure_time: "3:29 PM PDT",
        destination: "SFO",
        arrival_time: "4:59 PM PDT",
    },
    {
        airline: "SkyWest",
        flight_number: "3827",
        aircraft: "Embraer E170",
        origin: "LAX",
        departure_time: "2:51 PM PDT",
        destination: "SFO",
        arrival_time: "4:20 PM PDT",
    },
    {
        airline: "SkyWest",
        flight_number: "3453",
        aircraft: "Embraer E175",
        origin: "LAX",
        departure_time: "2:20 PM PDT",
        destination: "SFO",
        arrival_time: "3:51 PM PDT",
    },
    {
        airline: "SkyWest",
        flight_number: "3459",
        aircraft: "Embraer E175",
        origin: "LAX",
        departure_time: "1:05 PM PDT",
        destination: "SFO",
        arrival_time: "2:34 PM PDT",
    },
    {
        airline: "SkyWest",
        flight_number: "4646",
        aircraft: "Embraer E170",
        origin: "LAX",
        departure_time: "10:47 AM PDT",
        destination: "SFO",
        arrival_time: "12:09 PM PDT",
    },
    {
        airline: "JetBlue",
        flight_number: "2836",
        aircraft: "Airbus A320",
        origin: "LAX",
        departure_time: "10:28 AM PDT",
        destination: "SFO",
        arrival_time: "12:04 PM PDT",
    },
    {
        airline: "SkyWest",
        flight_number: "4006",
        aircraft: "Embraer E170",
        origin: "LAX",
        departure_time: "10:27 AM PDT",
        destination: "SFO",
        arrival_time: "12:03 PM PDT",
    },
    {
        airline: "SkyWest",
        flight_number: "3343",
        aircraft: "Embraer E175",
        origin: "LAX",
        departure_time: "10:00 AM PDT",
        destination: "SFO",
        arrival_time: "11:29 AM PDT",
    },
    {
        airline: "SkyWest",
        flight_number: "3319",
        aircraft: "Embraer E175",
        origin: "LAX",
        departure_time: "9:15 AM PDT",
        destination: "SFO",
        arrival_time: "10:44 AM PDT",
    },
    {
        airline: "United",
        flight_number: "501",
        aircraft: "Boeing 737-900",
        origin: "LAX",
        departure_time: "8:22 AM PDT",
        destination: "SFO",
        arrival_time: "9:48 AM PDT",
    },
    {
        airline: "SkyWest",
        flight_number: "3264",
        aircraft: "Bombardier CRJ700",
        origin: "LAX",
        departure_time: "8:19 AM PDT",
        destination: "SFO",
        arrival_time: "9:58 AM PDT",
    },
    {
        airline: "SkyWest",
        flight_number: "3634",
        aircraft: "Embraer E170",
        origin: "LAX",
        departure_time: "7:00 AM PDT",
        destination: "SFO",
        arrival_time: "8:33 AM PDT",
    },
    {
        airline: "SkyWest",
        flight_number: "3435",
        aircraft: "Embraer E175",
        origin: "LAX",
        departure_time: "7:00 AM PDT",
        destination: "SFO",
        arrival_time: "8:29 AM PDT",
    },
    {
        airline: "Southwest",
        flight_number: "2649",
        aircraft: "Boeing 737-800",
        origin: "LAX",
        departure_time: "6:45 AM PDT",
        destination: "SFO",
        arrival_time: "8:10 AM PDT",
    },
    {
        airline: "SkyWest",
        flight_number: "3324",
        aircraft: "Embraer E175",
        origin: "SFO",
        departure_time: "8:15 PM PDT",
        destination: "SAN",
        arrival_time: "9:45 PM PDT",
    },
    {
        airline: "Southwest",
        flight_number: "4150",
        aircraft: "Boeing 737-800",
        origin: "SFO",
        departure_time: "7:30 PM PDT",
        destination: "SAN",
        arrival_time: "9:10 PM PDT",
    },
    {
        airline: "United",
        flight_number: "2414",
        aircraft: "Airbus A319",
        origin: "SFO",
        departure_time: "6:38 PM PDT",
        destination: "SAN",
        arrival_time: "8:09 PM PDT",
    },
    {
        airline: "SkyWest",
        flight_number: "3330",
        aircraft: "Embraer E175",
        origin: "SFO",
        departure_time: "5:55 PM PDT",
        destination: "SAN",
        arrival_time: "7:25 PM PDT",
    },
    {
        airline: "SkyWest",
        flight_number: "3348",
        aircraft: "Embraer E175",
        origin: "SFO",
        departure_time: "3:45 PM PDT",
        destination: "SAN",
        arrival_time: "5:15 PM PDT",
    },
    {
        airline: "SkyWest",
        flight_number: "3302",
        aircraft: "Embraer E175",
        origin: "SFO",
        departure_time: "12:45 PM PDT",
        destination: "SAN",
        arrival_time: "2:15 PM PDT",
    },
    {
        airline: "Southwest",
        flight_number: "4105",
        aircraft: "Boeing 737-800",
        origin: "SFO",
        departure_time: "9:00 AM PDT",
        destination: "SAN",
        arrival_time: "10:45 AM PDT",
    },
    {
        airline: "SkyWest",
        flight_number: "3368",
        aircraft: "Embraer E175",
        origin: "SFO",
        departure_time: "8:50 AM PDT",
        destination: "SAN",
        arrival_time: "10:20 AM PDT",
    },
    {
        airline: "SkyWest",
        flight_number: "5279",
        aircraft: "Embraer E170",
        origin: "SFO",
        departure_time: "8:30 AM PDT",
        destination: "SAN",
        arrival_time: "10:04 AM PDT",
    },
    {
        airline: "SkyWest",
        flight_number: "3300",
        aircraft: "Embraer E175",
        origin: "SFO",
        departure_time: "7:00 AM PDT",
        destination: "SAN",
        arrival_time: "8:30 AM PDT",
    },
    {
        airline: "SkyWest",
        flight_number: "3361",
        aircraft: "Embraer E175",
        origin: "SAN",
        departure_time: "8:05 PM PDT",
        destination: "SFO",
        arrival_time: "9:43 PM PDT",
    },
    {
        airline: "SkyWest",
        flight_number: "3371",
        aircraft: "Embraer E175",
        origin: "SAN",
        departure_time: "5:55 PM PDT",
        destination: "SFO",
        arrival_time: "7:33 PM PDT",
    },
    {
        airline: "Southwest",
        flight_number: "4144",
        aircraft: "Boeing 737-800",
        origin: "SAN",
        departure_time: "5:05 PM PDT",
        destination: "SFO",
        arrival_time: "6:40 PM PDT",
    },
    {
        airline: "SkyWest",
        flight_number: "4676",
        aircraft: "Embraer E170",
        origin: "SAN",
        departure_time: "3:52 PM PDT",
        destination: "SFO",
        arrival_time: "5:27 PM PDT",
    },
    {
        airline: "SkyWest",
        flight_number: "3355",
        aircraft: "Embraer E175",
        origin: "SAN",
        departure_time: "3:35 PM PDT",
        destination: "SFO",
        arrival_time: "5:13 PM PDT",
    },
    {
        airline: "SkyWest",
        flight_number: "3389",
        aircraft: "Embraer E175",
        origin: "SAN",
        departure_time: "1:25 PM PDT",
        destination: "SFO",
        arrival_time: "2:35 PM PDT",
    },
    {
        airline: "SkyWest",
        flight_number: "3413",
        aircraft: "Embraer E175",
        origin: "SAN",
        departure_time: "11:00 AM PDT",
        destination: "SFO",
        arrival_time: "12:38 PM PDT",
    },
    {
        airline: "Southwest",
        flight_number: "4546",
        aircraft: "Boeing 737-700",
        origin: "SAN",
        departure_time: "7:55 AM PDT",
        destination: "SFO",
        arrival_time: "9:30 AM PDT",
    },
    {
        airline: "United",
        flight_number: "2480",
        aircraft: "Airbus A319",
        origin: "SAN",
        departure_time: "7:10 AM PDT",
        destination: "SFO",
        arrival_time: "8:38 AM PDT",
    },
    {
        airline: "SkyWest",
        flight_number: "3461",
        aircraft: "Embraer E175",
        origin: "SAN",
        departure_time: "6:30 AM PDT",
        destination: "SFO",
        arrival_time: "8:08 AM PDT",
    },
    {
        airline: "United",
        flight_number: "389",
        aircraft: "Airbus A320",
        origin: "SFO",
        departure_time: "6:45 PM PDT",
        destination: "PDX",
        arrival_time: "8:28 PM PDT",
    },
    {
        airline: "SkyWest",
        flight_number: "3388",
        aircraft: "Embraer E175",
        origin: "SFO",
        departure_time: "4:35 PM PDT",
        destination: "PDX",
        arrival_time: "6:17 PM PDT",
    },
    {
        airline: "Alaska Airlines",
        flight_number: "1301",
        aircraft: "Boeing 737-900",
        origin: "SFO",
        departure_time: "12:50 PM PDT",
        destination: "PDX",
        arrival_time: "2:34 PM PDT",
    },
    {
        airline: "United",
        flight_number: "609",
        aircraft: "Airbus A319",
        origin: "SFO",
        departure_time: "11:00 AM PDT",
        destination: "PDX",
        arrival_time: "12:47 PM PDT",
    },
    {
        airline: "SkyWest",
        flight_number: "3482",
        aircraft: "Embraer E175",
        origin: "SFO",
        departure_time: "9:45 AM PDT",
        destination: "PDX",
        arrival_time: "11:29 AM PDT",
    },
    {
        airline: "SkyWest",
        flight_number: "3381",
        aircraft: "Embraer E175",
        origin: "SFO",
        departure_time: "7:00 AM PDT",
        destination: "PDX",
        arrival_time: "8:44 AM PDT",
    },
    {
        airline: "Alaska Airlines",
        flight_number: "1303",
        aircraft: "Boeing 737-800",
        origin: "PDX",
        departure_time: "5:50 PM PDT",
        destination: "SFO",
        arrival_time: "7:35 PM PDT",
    },
    {
        airline: "United",
        flight_number: "1687",
        aircraft: "Airbus A319",
        origin: "PDX",
        departure_time: "3:45 PM PDT",
        destination: "SFO",
        arrival_time: "5:32 PM PDT",
    },
    {
        airline: "SkyWest",
        flight_number: "3342",
        aircraft: "Embraer E175",
        origin: "PDX",
        departure_time: "2:55 PM PDT",
        destination: "SFO",
        arrival_time: "4:37 PM PDT",
    },
    {
        airline: "SkyWest",
        flight_number: "3483",
        aircraft: "Embraer E175",
        origin: "PDX",
        departure_time: "12:10 PM PDT",
        destination: "SFO",
        arrival_time: "1:53 PM PDT",
    },
    {
        airline: "Alaska Airlines",
        flight_number: "430",
        aircraft: "Airbus A320",
        origin: "PDX",
        departure_time: "8:55 AM PDT",
        destination: "SFO",
        arrival_time: "10:40 AM PDT",
    },
    {
        airline: "United",
        flight_number: "1491",
        aircraft: "Airbus A319",
        origin: "PDX",
        departure_time: "7:40 AM PDT",
        destination: "SFO",
        arrival_time: "9:26 AM PDT",
    },
    {
        airline: "SkyWest",
        flight_number: "3431",
        aircraft: "Embraer E175",
        origin: "PDX",
        departure_time: "6:35 AM PDT",
        destination: "SFO",
        arrival_time: "8:18 AM PDT",
    },
    {
        airline: "United",
        flight_number: "620",
        aircraft: "Airbus A320",
        origin: "SFO",
        departure_time: "6:40 PM PDT",
        destination: "SEA",
        arrival_time: "8:46 PM PDT",
    },
    {
        airline: "SkyWest",
        flight_number: "3722",
        aircraft: "Embraer E170",
        origin: "SFO",
        departure_time: "5:40 PM PDT",
        destination: "SEA",
        arrival_time: "7:58 PM PDT",
    },
    {
        airline: "Alaska Airlines",
        flight_number: "411",
        aircraft: "Airbus A320",
        origin: "SFO",
        departure_time: "4:45 PM PDT",
        destination: "SEA",
        arrival_time: "6:45 PM PDT",
    },
    {
        airline: "SkyWest",
        flight_number: "3599",
        aircraft: "Embraer E170",
        origin: "SFO",
        departure_time: "2:59 PM PDT",
        destination: "SEA",
        arrival_time: "5:22 PM PDT",
    },
    {
        airline: "Alaska Airlines",
        flight_number: "1477",
        aircraft: "Airbus A321",
        origin: "SFO",
        departure_time: "11:10 AM PDT",
        destination: "SEA",
        arrival_time: "1:20 PM PDT",
    },
    {
        airline: "United",
        flight_number: "277",
        aircraft: "Airbus A319",
        origin: "SFO",
        departure_time: "10:40 AM PDT",
        destination: "SEA",
        arrival_time: "12:54 PM PDT",
    },
    {
        airline: "SkyWest",
        flight_number: "3716",
        aircraft: "Embraer E175",
        origin: "SFO",
        departure_time: "10:30 AM PDT",
        destination: "SEA",
        arrival_time: "12:55 PM PDT",
    },
    {
        airline: "Horizon",
        flight_number: "2257",
        aircraft: "Embraer E175",
        origin: "SFO",
        departure_time: "9:25 AM PDT",
        destination: "SEA",
        arrival_time: "11:35 AM PDT",
    },
    {
        airline: "Alaska Airlines",
        flight_number: "1243",
        aircraft: "Boeing 737-900",
        origin: "SFO",
        departure_time: "8:00 AM PDT",
        destination: "SEA",
        arrival_time: "10:10 AM PDT",
    },
    {
        airline: "Alaska Airlines",
        flight_number: "1189",
        aircraft: "Boeing 737-800",
        origin: "SFO",
        departure_time: "7:00 AM PDT",
        destination: "SEA",
        arrival_time: "9:12 AM PDT",
    },
    {
        airline: "SkyWest",
        flight_number: "3566",
        aircraft: "Embraer E170",
        origin: "SFO",
        departure_time: "6:30 AM PDT",
        destination: "SEA",
        arrival_time: "8:55 AM PDT",
    },
    {
        airline: "Alaska Airlines",
        flight_number: "373",
        aircraft: "Boeing 737-900",
        origin: "SFO",
        departure_time: "6:00 AM PDT",
        destination: "SEA",
        arrival_time: "8:10 AM PDT",
    },
    {
        airline: "Alaska Airlines",
        flight_number: "376",
        aircraft: "Boeing 737-900",
        origin: "SEA",
        departure_time: "7:45 PM PDT",
        destination: "SFO",
        arrival_time: "9:53 PM PDT",
    },
    {
        airline: "SkyWest",
        flight_number: "3560",
        aircraft: "Embraer E170",
        origin: "SEA",
        departure_time: "7:25 PM PDT",
        destination: "SFO",
        arrival_time: "9:42 PM PDT",
    },
    {
        airline: "Alaska Airlines",
        flight_number: "1258",
        aircraft: "Airbus A321",
        origin: "SEA",
        departure_time: "5:50 PM PDT",
        destination: "SFO",
        arrival_time: "7:58 PM PDT",
    },
    {
        airline: "United",
        flight_number: "2050",
        aircraft: "Airbus A319",
        origin: "SEA",
        departure_time: "3:04 PM PDT",
        destination: "SFO",
        arrival_time: "5:09 PM PDT",
    },
    {
        airline: "SkyWest",
        flight_number: "3594",
        aircraft: "Embraer E170",
        origin: "SEA",
        departure_time: "2:10 PM PDT",
        destination: "SFO",
        arrival_time: "4:32 PM PDT",
    },
    {
        airline: "Alaska Airlines",
        flight_number: "1252",
        aircraft: "Airbus A320",
        origin: "SEA",
        departure_time: "1:40 PM PDT",
        destination: "SFO",
        arrival_time: "3:45 PM PDT",
    },
    {
        airline: "SkyWest",
        flight_number: "3751",
        aircraft: "Embraer E170",
        origin: "SEA",
        departure_time: "11:45 AM PDT",
        destination: "SFO",
        arrival_time: "2:09 PM PDT",
    },
    {
        airline: "Alaska Airlines",
        flight_number: "1350",
        aircraft: "Boeing 737-900",
        origin: "SEA",
        departure_time: "11:25 AM PDT",
        destination: "SFO",
        arrival_time: "1:35 PM PDT",
    },
    {
        airline: "Alaska Airlines",
        flight_number: "405",
        aircraft: "Airbus A321",
        origin: "SEA",
        departure_time: "8:00 AM PDT",
        destination: "SFO",
        arrival_time: "10:10 AM PDT",
    },
    {
        airline: "United",
        flight_number: "2499",
        aircraft: "Airbus A320",
        origin: "SEA",
        departure_time: "7:20 AM PDT",
        destination: "SFO",
        arrival_time: "9:27 AM PDT",
    },
    {
        airline: "SkyWest",
        flight_number: "3708",
        aircraft: "Embraer E170",
        origin: "SEA",
        departure_time: "7:15 AM PDT",
        destination: "SFO",
        arrival_time: "9:39 AM PDT",
    },
    {
        airline: "Horizon",
        flight_number: "2071",
        aircraft: "Embraer E175",
        origin: "SEA",
        departure_time: "6:35 AM PDT",
        destination: "SFO",
        arrival_time: "8:38 AM PDT",
    },
    {
        airline: "SkyWest",
        flight_number: "5458",
        aircraft: "Embraer E170",
        origin: "SFO",
        departure_time: "6:30 PM PDT",
        destination: "PHX",
        arrival_time: "8:30 PM MST",
    },
    {
        airline: "American Airlines",
        flight_number: "843",
        aircraft: "Airbus A319",
        origin: "SFO",
        departure_time: "4:07 PM PDT",
        destination: "PHX",
        arrival_time: "6:19 PM MST",
    },
    {
        airline: "Southwest",
        flight_number: "3766",
        aircraft: "Boeing 737-800",
        origin: "SFO",
        departure_time: "3:45 PM PDT",
        destination: "PHX",
        arrival_time: "5:50 PM MST",
    },
    {
        airline: "SkyWest",
        flight_number: "3412",
        aircraft: "Embraer E175",
        origin: "SFO",
        departure_time: "2:50 PM PDT",
        destination: "PHX",
        arrival_time: "4:50 PM PDT",
    },
    {
        airline: "American Airlines",
        flight_number: "2523",
        aircraft: "Airbus A319",
        origin: "SFO",
        departure_time: "1:34 PM PDT",
        destination: "PHX",
        arrival_time: "3:51 PM MST",
    },
    {
        airline: "American Airlines",
        flight_number: "2018",
        aircraft: "Airbus A321",
        origin: "SFO",
        departure_time: "9:59 AM PDT",
        destination: "PHX",
        arrival_time: "12:07 PM MST",
    },
    {
        airline: "United",
        flight_number: "623",
        aircraft: "Airbus A319",
        origin: "SFO",
        departure_time: "9:15 AM PDT",
        destination: "PHX",
        arrival_time: "11:08 AM MST",
    },
    {
        airline: "American Airlines",
        flight_number: "2042",
        aircraft: "Airbus A320",
        origin: "SFO",
        departure_time: "6:09 AM PDT",
        destination: "PHX",
        arrival_time: "8:21 AM MST",
    },
    {
        airline: "Southwest",
        flight_number: "747",
        aircraft: "Boeing 737-800",
        origin: "SFO",
        departure_time: "6:00 AM PDT",
        destination: "PHX",
        arrival_time: "8:00 AM MST",
    },
    {
        airline: "Southwest",
        flight_number: "588",
        aircraft: "Boeing 737-700",
        origin: "PHX",
        departure_time: "8:55 PM MST",
        destination: "SFO",
        arrival_time: "11:00 PM PDT",
    },
    {
        airline: "American Airlines",
        flight_number: "597",
        aircraft: "Airbus A321",
        origin: "PHX",
        departure_time: "7:27 PM MST",
        destination: "SFO",
        arrival_time: "9:40 PM PDT",
    },
    {
        airline: "SkyWest",
        flight_number: "3312",
        aircraft: "Embraer E175",
        origin: "PHX",
        departure_time: "5:30 PM MST",
        destination: "SFO",
        arrival_time: "7:29 PM PDT",
    },
    {
        airline: "American Airlines",
        flight_number: "686",
        aircraft: "Airbus A320",
        origin: "PHX",
        departure_time: "3:35 PM MST",
        destination: "SFO",
        arrival_time: "5:47 PM PDT",
    },
    {
        airline: "United",
        flight_number: "570",
        aircraft: "Airbus A319",
        origin: "PHX",
        departure_time: "3:00 PM MST",
        destination: "SFO",
        arrival_time: "5:02 PM PDT",
    },
    {
        airline: "American Airlines",
        flight_number: "2016",
        aircraft: "Airbus A319",
        origin: "PHX",
        departure_time: "11:02 AM MST",
        destination: "SFO",
        arrival_time: "1:13 PM PDT",
    },
    {
        airline: "Southwest",
        flight_number: "3651",
        aircraft: "Boeing 737-700",
        origin: "PHX",
        departure_time: "8:45 AM MST",
        destination: "SFO",
        arrival_time: "10:55 AM PDT",
    },
    {
        airline: "American Airlines",
        flight_number: "2542",
        aircraft: "Airbus A319",
        origin: "PHX",
        departure_time: "8:41 AM MST",
        destination: "SFO",
        arrival_time: "10:55 AM PDT",
    },
    {
        airline: "SkyWest",
        flight_number: "5437",
        aircraft: "Embraer E170",
        origin: "PHX",
        departure_time: "7:18 AM MST",
        destination: "SFO",
        arrival_time: "9:30 AM PST",
    },
    {
        airline: "SkyWest",
        flight_number: "5606",
        aircraft: "Bombardier CRJ200",
        origin: "SFO",
        departure_time: "6:25 PM PDT",
        destination: "TUS",
        arrival_time: "8:30 PM MST",
    },
    {
        airline: "SkyWest",
        flight_number: "5442",
        aircraft: "Bombardier CRJ200",
        origin: "SFO",
        departure_time: "10:45 AM PDT",
        destination: "TUS",
        arrival_time: "12:52 PM MST",
    },
    {
        airline: "SkyWest",
        flight_number: "5354",
        aircraft: "Embraer E170",
        origin: "TUS",
        departure_time: "3:21 PM MST",
        destination: "SFO",
        arrival_time: "5:38 PM PDT",
    },
    {
        airline: "SkyWest",
        flight_number: "5856",
        aircraft: "Bombardier CRJ200",
        origin: "TUS",
        departure_time: "7:13 AM MST",
        destination: "SFO",
        arrival_time: "9:34 AM PDT",
    },
    {
        airline: "SkyWest",
        flight_number: "3408",
        aircraft: "Embraer E175",
        origin: "SFO",
        departure_time: "8:15 PM PDT",
        destination: "LAS",
        arrival_time: "9:46 PM PDT",
    },
    {
        airline: "United",
        flight_number: "394",
        aircraft: "Airbus A320",
        origin: "SFO",
        departure_time: "6:39 PM PDT",
        destination: "LAS",
        arrival_time: "8:10 PM PDT",
    },
    {
        airline: "SkyWest",
        flight_number: "3438",
        aircraft: "Embraer E175",
        origin: "SFO",
        departure_time: "6:15 PM PDT",
        destination: "LAS",
        arrival_time: "7:46 PM PDT",
    },
    {
        airline: "Southwest",
        flight_number: "3428",
        aircraft: "Boeing 737-800",
        origin: "SFO",
        departure_time: "2:50 PM PDT",
        destination: "LAS",
        arrival_time: "4:30 PM PDT",
    },
    {
        airline: "SkyWest",
        flight_number: "3326",
        aircraft: "Embraer E175",
        origin: "SFO",
        departure_time: "1:25 PM PDT",
        destination: "LAS",
        arrival_time: "2:56 PM PDT",
    },
    {
        airline: "Frontier",
        flight_number: "2078",
        aircraft: "Airbus A321",
        origin: "SFO",
        departure_time: "10:54 AM PDT",
        destination: "LAS",
        arrival_time: "12:31 PM PDT",
    },
    {
        airline: "United",
        flight_number: "358",
        aircraft: "Boeing 737-900",
        origin: "SFO",
        departure_time: "10:52 AM PDT",
        destination: "LAS",
        arrival_time: "12:27 PM PDT",
    },
    {
        airline: "Southwest",
        flight_number: "4549",
        aircraft: "Boeing 737-700",
        origin: "SFO",
        departure_time: "10:05 AM PDT",
        destination: "LAS",
        arrival_time: "11:40 AM PDT",
    },
    {
        airline: "SkyWest",
        flight_number: "3471",
        aircraft: "Embraer E175",
        origin: "SFO",
        departure_time: "10:00 AM PDT",
        destination: "LAS",
        arrival_time: "11:31 AM PDT",
    },
    {
        airline: "SkyWest",
        flight_number: "3438",
        aircraft: "Embraer E175",
        origin: "LAS",
        departure_time: "8:30 PM PDT",
        destination: "SFO",
        arrival_time: "10:03 PM PDT",
    },
    {
        airline: "Southwest",
        flight_number: "383",
        aircraft: "Boeing 737 MAX 8",
        origin: "LAS",
        departure_time: "8:20 PM PDT",
        destination: "SFO",
        arrival_time: "9:50 PM PDT",
    },
    {
        airline: "United",
        flight_number: "2047",
        aircraft: "Boeing 737-900",
        origin: "LAS",
        departure_time: "3:59 PM PDT",
        destination: "SFO",
        arrival_time: "5:28 PM PDT",
    },
    {
        airline: "SkyWest",
        flight_number: "3313",
        aircraft: "Embraer E175",
        origin: "LAS",
        departure_time: "3:40 PM PDT",
        destination: "SFO",
        arrival_time: "5:13 PM PDT",
    },
    {
        airline: "Southwest",
        flight_number: "3429",
        aircraft: "Boeing 737-800",
        origin: "LAS",
        departure_time: "12:30 PM PDT",
        destination: "SFO",
        arrival_time: "2:05 PM PDT",
    },
    {
        airline: "SkyWest",
        flight_number: "3469",
        aircraft: "Embraer E175",
        origin: "LAS",
        departure_time: "12:15 PM PDT",
        destination: "SFO",
        arrival_time: "1:50 PM PDT",
    },
    {
        airline: "Frontier",
        flight_number: "2079",
        aircraft: "Airbus A321",
        origin: "LAS",
        departure_time: "8:16 AM PDT",
        destination: "SFO",
        arrival_time: "9:56 AM PDT",
    },
    {
        airline: "United",
        flight_number: "427",
        aircraft: "Airbus A320",
        origin: "LAS",
        departure_time: "8:01 AM PDT",
        destination: "SFO",
        arrival_time: "9:32 AM PDT",
    },
    {
        airline: "SkyWest",
        flight_number: "3308",
        aircraft: "Embraer E175",
        origin: "LAS",
        departure_time: "7:45 AM PDT",
        destination: "SFO",
        arrival_time: "9:20 AM PDT",
    },
    {
        airline: "SkyWest",
        flight_number: "3765",
        aircraft: "Embraer E170",
        origin: "SFO",
        departure_time: "7:13 PM PDT",
        destination: "SLC",
        arrival_time: "10:10 PM MDT",
    },
    {
        airline: "SkyWest",
        flight_number: "5879",
        aircraft: "Bombardier CRJ700",
        origin: "SFO",
        departure_time: "6:26 PM PDT",
        destination: "SLC",
        arrival_time: "9:12 PM MDT",
    },
    {
        airline: "Delta",
        flight_number: "1380",
        aircraft: "Airbus A220-300",
        origin: "SFO",
        departure_time: "5:32 PM PDT",
        destination: "SLC",
        arrival_time: "8:25 PM MDT",
    },
    {
        airline: "Delta",
        flight_number: "1317",
        aircraft: "Airbus A220-300",
        origin: "SFO",
        departure_time: "1:58 PM PDT",
        destination: "SLC",
        arrival_time: "4:53 PM MDT",
    },
    {
        airline: "Delta",
        flight_number: "1303",
        aircraft: "Airbus A220-300",
        origin: "SFO",
        departure_time: "10:36 AM PDT",
        destination: "SLC",
        arrival_time: "1:25 PM MDT",
    },
    {
        airline: "SkyWest",
        flight_number: "3448",
        aircraft: "Embraer E175",
        origin: "SFO",
        departure_time: "10:10 AM PDT",
        destination: "SLC",
        arrival_time: "1:05 PM MDT",
    },
    {
        airline: "SkyWest",
        flight_number: "5631",
        aircraft: "Embraer E170",
        origin: "SFO",
        departure_time: "8:55 AM PDT",
        destination: "SLC",
        arrival_time: "11:48 AM MDT",
    },
    {
        airline: "Delta",
        flight_number: "1211",
        aircraft: "Airbus A319",
        origin: "SFO",
        departure_time: "6:00 AM PDT",
        destination: "SLC",
        arrival_time: "8:52 AM MDT",
    },
    {
        airline: "Delta",
        flight_number: "2104",
        aircraft: "Airbus A319",
        origin: "SLC",
        departure_time: "10:40 PM MDT",
        destination: "SFO",
        arrival_time: "11:44 PM PDT",
    },
    {
        airline: "SkyWest",
        flight_number: "3765",
        aircraft: "Embraer E170",
        origin: "SLC",
        departure_time: "5:23 PM MDT",
        destination: "SFO",
        arrival_time: "6:23 PM PDT",
    },
    {
        airline: "Delta",
        flight_number: "1352",
        aircraft: "Airbus A220-300",
        origin: "SLC",
        departure_time: "3:15 PM MDT",
        destination: "SFO",
        arrival_time: "4:15 PM PDT",
    },
    {
        airline: "Delta",
        flight_number: "1317",
        aircraft: "Airbus A220-300",
        origin: "SLC",
        departure_time: "11:40 AM MDT",
        destination: "SFO",
        arrival_time: "12:40 PM PDT",
    },
    {
        airline: "SkyWest",
        flight_number: "3437",
        aircraft: "Embraer E175",
        origin: "SLC",
        departure_time: "11:35 AM MDT",
        destination: "SFO",
        arrival_time: "12:43 PM PDT",
    },
    {
        airline: "Delta",
        flight_number: "1303",
        aircraft: "Airbus A220-300",
        origin: "SLC",
        departure_time: "8:15 AM MDT",
        destination: "SFO",
        arrival_time: "9:21 AM PDT",
    },
    {
        airline: "SkyWest",
        flight_number: "5736",
        aircraft: "Embraer E170",
        origin: "SLC",
        departure_time: "8:00 AM MDT",
        destination: "SFO",
        arrival_time: "9:12 AM PDT",
    },
    {
        airline: "SkyWest",
        flight_number: "5287",
        aircraft: "Embraer E170",
        origin: "SLC",
        departure_time: "6:00 AM MDT",
        destination: "SFO",
        arrival_time: "7:09 AM PDT",
    },
    {
        airline: "United",
        flight_number: "1968",
        aircraft: "Airbus A319",
        origin: "SFO",
        departure_time: "6:30 PM PDT",
        destination: "DEN",
        arrival_time: "10:01 PM MDT",
    },
    {
        airline: "Frontier",
        flight_number: "664",
        aircraft: "Airbus A320",
        origin: "SFO",
        departure_time: "1:09 PM PDT",
        destination: "DEN",
        arrival_time: "4:58 PM MDT",
    },
    {
        airline: "United",
        flight_number: "720",
        aircraft: "Boeing 737-900",
        origin: "SFO",
        departure_time: "1:05 PM PDT",
        destination: "DEN",
        arrival_time: "4:41 PM MDT",
    },
    {
        airline: "Southwest",
        flight_number: "2912",
        aircraft: "Boeing 737-800",
        origin: "SFO",
        departure_time: "12:50 PM PDT",
        destination: "DEN",
        arrival_time: "4:25 PM MDT",
    },
    {
        airline: "United",
        flight_number: "320",
        aircraft: "Airbus A319",
        origin: "SFO",
        departure_time: "10:50 AM PDT",
        destination: "DEN",
        arrival_time: "2:25 PM MDT",
    },
    {
        airline: "United",
        flight_number: "313",
        aircraft: "Boeing 737-900",
        origin: "SFO",
        departure_time: "8:50 AM PDT",
        destination: "DEN",
        arrival_time: "12:25 PM MDT",
    },
    {
        airline: "Southwest",
        flight_number: "4602",
        aircraft: "Boeing 737 MAX 8",
        origin: "SFO",
        departure_time: "6:10 AM PDT",
        destination: "DEN",
        arrival_time: "9:50 AM MDT",
    },
    {
        airline: "United",
        flight_number: "602",
        aircraft: "Boeing 757-200",
        origin: "SFO",
        departure_time: "5:30 AM PDT",
        destination: "DEN",
        arrival_time: "9:02 AM MDT",
    },
    {
        airline: "Frontier",
        flight_number: "662",
        aircraft: "Airbus A320",
        origin: "SFO",
        departure_time: "12:59 AM PDT",
        destination: "DEN",
        arrival_time: "4:33 AM MDT",
    },
    {
        airline: "Frontier",
        flight_number: "667",
        aircraft: "Airbus A320",
        origin: "DEN",
        departure_time: "10:10 PM MDT",
        destination: "SFO",
        arrival_time: "11:58 PM PDT",
    },
    {
        airline: "Southwest",
        flight_number: "3334",
        aircraft: "Boeing 737-800",
        origin: "DEN",
        departure_time: "9:00 PM MDT",
        destination: "SFO",
        arrival_time: "10:45 PM PDT",
    },
    {
        airline: "United",
        flight_number: "490",
        aircraft: "Boeing 757-200",
        origin: "DEN",
        departure_time: "7:45 PM MDT",
        destination: "SFO",
        arrival_time: "9:26 PM PDT",
    },
    {
        airline: "United",
        flight_number: "735",
        aircraft: "Airbus A319",
        origin: "DEN",
        departure_time: "3:56 PM MDT",
        destination: "SFO",
        arrival_time: "5:33 PM PDT",
    },
    {
        airline: "Southwest",
        flight_number: "3765",
        aircraft: "Boeing 737 MAX 8",
        origin: "DEN",
        departure_time: "1:20 PM MDT",
        destination: "SFO",
        arrival_time: "3:00 PM PDT",
    },
    {
        airline: "United",
        flight_number: "1561",
        aircraft: "Boeing 737-700",
        origin: "DEN",
        departure_time: "11:15 AM MDT",
        destination: "SFO",
        arrival_time: "12:54 PM PDT",
    },
    {
        airline: "Frontier",
        flight_number: "663",
        aircraft: "Airbus A320",
        origin: "DEN",
        departure_time: "10:20 AM MDT",
        destination: "SFO",
        arrival_time: "12:06 PM PDT",
    },
    {
        airline: "United",
        flight_number: "1068",
        aircraft: "Airbus A319",
        origin: "DEN",
        departure_time: "10:00 AM MDT",
        destination: "SFO",
        arrival_time: "11:40 AM PDT",
    },
    {
        airline: "United",
        flight_number: "419",
        aircraft: "Boeing 737-700",
        origin: "DEN",
        departure_time: "8:00 AM MDT",
        destination: "SFO",
        arrival_time: "9:39 AM PDT",
    },
    {
        airline: "SkyWest",
        flight_number: "5448",
        aircraft: "Bombardier CRJ200",
        origin: "SFO",
        departure_time: "11:25 AM PDT",
        destination: "ABQ",
        arrival_time: "2:46 PM MDT",
    },
    {
        airline: "SkyWest",
        flight_number: "5439",
        aircraft: "Bombardier CRJ200",
        origin: "ABQ",
        departure_time: "3:58 PM MDT",
        destination: "SFO",
        arrival_time: "5:44 PM PDT",
    },
    {
        airline: "SkyWest",
        flight_number: "3366",
        aircraft: "Embraer E175",
        origin: "SFO",
        departure_time: "6:45 PM PDT",
        destination: "BOI",
        arrival_time: "9:25 PM MDT",
    },
    {
        airline: "SkyWest",
        flight_number: "5327",
        aircraft: "Embraer E170",
        origin: "SFO",
        departure_time: "6:25 PM PDT",
        destination: "BOI",
        arrival_time: "9:01 PM MDT",
    },
    {
        airline: "SkyWest",
        flight_number: "5328",
        aircraft: "Bombardier CRJ200",
        origin: "SFO",
        departure_time: "10:35 AM PDT",
        destination: "BOI",
        arrival_time: "1:15 PM MDT",
    },
    {
        airline: "SkyWest",
        flight_number: "5321",
        aircraft: "Bombardier CRJ200",
        origin: "BOI",
        departure_time: "4:55 PM MDT",
        destination: "SFO",
        arrival_time: "5:50 PM PDT",
    },
    {
        airline: "SkyWest",
        flight_number: "3357",
        aircraft: "Embraer E175",
        origin: "BOI",
        departure_time: "8:30 AM MDT",
        destination: "SFO",
        arrival_time: "9:20 AM PDT",
    },
    {
        airline: "SkyWest",
        flight_number: "5745",
        aircraft: "Embraer E170",
        origin: "BOI",
        departure_time: "7:00 AM MDT",
        destination: "SFO",
        arrival_time: "7:49 AM PDT",
    },
  ]


  def self.flights
    @flights
  end
end